title: Doc Projet
description: Documentation du projet

# NE RIEN MODIFIER CI-DESSOUS SI VOUS N'ETES PAS CERTAINS DE CE QUE VOUS FAITES

# Thème
# remote_theme: Makerspace-Amiens/CraftTheDocs-V1.0
theme: so-simple-theme
url: https://github.com/Makerspace-Amiens

# Paramètres optionnels de "Just the Docs"
so-simple-theme:
  navigation_depth: 5
  search_enabled: true
  search_indexing: true
